routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\CategorieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::get('/catalogue/search',[HomeController::class,'search'])->name("home.search");
Route::get('/commandes/search',[CommandeController::class,"search"])->name('commandes.search');
Route::get('/commandes/exportCSV',[CommandeController::class,"exportCSV"])->name('commandes.exportCSV');
Route::resource("categories",CategorieController::class);
Route::resource("clients",ClientController::class);
Route::resource("produits",ProduitController::class);
Route::resource("commandes",CommandeController::class);

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;
    protected $fillable=[
        'nom',
        'prenom',
        'tele',
        'ville',
        'adresse'
    ];

    public function commandes(){
        return $this->hasMany(Commande::class);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;
use App\Models\Client;

use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/clients/create.blade.php
@extends('layouts.admin')
@section('title','Gestion des categories')
@section('content')
<form action="{{route('commandes.store')}}" method="post">
    @csrf
    <div>
        <label for="nom">Nom</label>
        <input type="text" id="nom" name="nom"/>
    </div>
    <div>
        <label for="prenom">Prenom</label>
        <input type="text" id="prenom" name="prenom"/>
    </div>
    <div>
        <label for="tele">Tele</label>
        <input type="text" id="tele" name="tele"/>
    </div>
    <div>
        <label for="ville">Ville</label>
        <input type="text" id="ville" name="ville"/>
    </div>
    <div>
        <label for="adresse">Adresse</label>
        <input type="text" id="adresse" name="adresse"/>
    </div>
    
    <div>
        <input type="submit" value="Enregistrer">
    </div>
</form>
@endsection