routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\CategorieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::get('/catalogue/search',[HomeController::class,'search'])->name("home.search");
Route::get('/commandes/search',[CommandeController::class,"search"])->name('commandes.search');
Route::get('/commandes/exportCSV',[CommandeController::class,"exportCSV"])->name('commandes.exportCSV');
Route::resource("categories",CategorieController::class);
Route::resource("clients",ClientController::class);
Route::resource("produits",ProduitController::class);
Route::resource("commandes",CommandeController::class);

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('css/main.css')}}">
    <title>@yield('title','App store')</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{{route('home.index')}}">Catalogue</a></li>
            <li><a href="{{route('categories.index')}}">Gestion des categories</a></li>
            <li><a href="{{route('produits.index')}}">Gestion des produits</a></li>
            <li><a href="{{route('commandes.index')}}">Suivi des commandes</a></li>
            <li><a href="{{route('home.panier')}}">Mon panier</a></li>
        </ul>
    </nav>
    <div class="main">
        @yield('content')
    </div>
    <footer>
        &copy;OFPPT 2024
    </footer>
</body>
</html>