routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\CategorieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::get('/catalogue/search',[HomeController::class,'search'])->name("home.search");
Route::get('/commandes/search',[CommandeController::class,"search"])->name('commandes.search');
Route::get('/commandes/exportCSV',[CommandeController::class,"exportCSV"])->name('commandes.exportCSV');
Route::resource("categories",CategorieController::class);
Route::resource("clients",ClientController::class);
Route::resource("produits",ProduitController::class);
Route::resource("commandes",CommandeController::class);

app/Models/Produit.php
<?php

namespace App\Models;

use App\Models\Categorie;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Produit extends Model
{
    use HasFactory;
    protected $fillable =[
        'designation',
        'prix_u',
        'quantite_stock',
        'categorie_id',
        'image'
    ];
    public function categorie(){
       return  $this->belongsTo(Categorie::class);
    }

    public function commandes(){
        return $this->belongsToMany(Commande::class)
                    ->using(LigneDeCommande::class)
                    ->withPivot('quantite');
    }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;
use App\Models\Produit;
use App\Models\Categorie;

use Illuminate\Http\Request;

class ProduitController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        //
            $list_categories=Categorie::select('id','designation')->get();
            $des=$request->query('designation');
            $prix_min=$request->query('prix_u_min');
            $prix_max=$request->query('prix_u_max');
            $quantite=$request->query('quantite_stock');
            $categorie_id=$request->query('categorie_id');

            $p=Produit::query();
            if($des){
                $p->where('designation','like','%'.$des.'%');
            }
            if($prix_min){
                $p->where('prix_u','>',$prix_min);
            }
            if($prix_max){
                $p->where('prix_u','<',$prix_max);

            }
            if($quantite){
                $p->where('quantite_stock','>',$quantite);
            }
            if($categorie_id){
                $p->where('categorie_id','=',$categorie_id);
            }
            $produits=$p->paginate(5);
            $produits->appends([
                'designation'=>$des,
                'prix_u_min'=>$prix_min,
                'prix_u_max'=>$prix_max,
                'quantite_stock'=>$quantite,
                'categorie_id'=>$categorie_id
            ]);
            return view('produits.index',compact('produits','list_categories'));
            
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        $list_categories=Categorie::select('id','designation')->get();
        return view('produits.create',compact('list_categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        $validatedData=$request->validate(
            [
                'designation'=>'required|unique:produits,designation',
                'prix_u'=>'required',
                'quantite_stock'=>'required',
                'categorie_id'=>'required',
                'image'=>'image|mimes:jpeg,png,jpg,gif,svg|max:80000',
            ]
            );
            if($request->hasFile('image')){
                $imagePath=$request->file('image')->store('products/images','public');
                $validatedData['image']=$imagePath;
            }
        Produit::create($validatedData);
        return redirect()->route('produits.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
        $produit=Produit::find($id)->load('categorie');
        if($produit){
            return view('produits.show',compact('produit'));
        }
        else {
            abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
        $produit=Produit::find($id);
        if($produit){
            $list_categories=Categorie::select('id','designation')->get();
            return view('produits.edit',compact('produit','list_categories'));
        }
        else {
            abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
        $validatedData=$request->validate(
            [
                'designation'=>'required|unique:produits,designation,'.$id,
                'prix_u'=>'required',
                'quantite_stock'=>'required',
                'categorie_id'=>'required',
                'image'=>'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]
            );
            if($request->hasFile('image')){
                $imagePath=$request->file('image')->store('products/images','public');
                $validatedData['image']=$imagePath;
            }
        $produit=Produit::find($id);
        $produit->update($validatedData);
        return redirect()->route('produits.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
        Produit::destroy($id);
        return redirect()->route('produits.index');
    }
}

resources/views/produits/create.blade.php
@extends('layouts.admin')
 @section('title','Ajouter un produit')
 @section('content')
<h1>Ajouter un nouveau produit</h1>
<form action="{{route('produits.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <div>
        <label for="designation">Designation</label>
        <input type="text" id="designation" name="designation" value="{{old('designation')}}">

        
    </div>
    <div>
        <label for="prix_u">Prix unitaire</label>
        <input type="text" id="prix_u" name="prix_u" value="{{old('prix_u')}}">
    </div>
    <div>
        <label for="quantite_stock">Quantite stock</label>
        <input type="number" min=0 max=9999 id="quantite_stock" name="quantite_stock" value="{{old('quantite_stock')}}">
    </div>
    <div>
        <label for="categorie">Categorie</label>
        <select name="categorie_id" id="categorie">
            <option value="">Choisir...</option>
            @foreach($list_categories as $cat)
                <option value="{{$cat->id}}">{{$cat->designation}}</option>
            @endforeach
        </select>
    </div>
    <div>
        <label for="image">Image</label>
        <input type="file" name="image" id="image" accept="images/*">
    </div>
    <div>
        <input type="submit" value="Ajouter">
    </div>
</form>

    @if($errors->any())
        @foreach($errors->all() as $er)
        <div>{{$er}}</div> 

        @endforeach

    @endif
    

    
@endsection

resources/views/produits/edit.blade.php
@extends('layouts.admin')
 @section('title','Modifier un produit')
 @section('content')
    <form action="{{route('produits.update',$produit->id)}}" method="post" enctype="multipart/form-data">
        @method('put')
        @csrf
    <div>
        <label for="designation">Designation</label>
        <input type="text" id="designation" name="designation" value="{{old('designation',$produit->designation)}}">
    </div>
    <div>
        <label for="prix_u">Prix unitaire</label>
        <input type="text" id="prix_u" name="prix_u" value="{{old('prix_u',$produit->prix_u)}}">
    </div>
    <div>
        <label for="quantite_stock">Quantite stock</label>
        <input type="number" min=0 max=9999 id="quantite_stock" name="quantite_stock" value="{{old('quantite_stock',$produit->quantite_stock)}}">
    </div>
    <div>
        <label for="categorie">Categorie</label>
        <select name="categorie_id" id="categorie" value="{{old('categorie_id',$produit->categorie_id)}}">
            @foreach($list_categories as $cat)
                <option value="{{$cat->id}}">{{$cat->designation}}</option>
            @endforeach
        </select>
    </div>
    <div>
        <label for="image">Image</label>
        <input type="file" name="image" id="image" accept="images/*">
    </div>
    <div>
        <input type="submit" value="Modifier">
    </div>
    </form>
    
@endsection

resources/views/produits/index.blade.php
@extends('layouts.admin')
 @section('title','Afficher tous les produits')
 @section('content')
    <div>
      <form action="{{route('produits.index')}}" method="get">
        
        
        <input type="text" name="designation" id="designation" placeholder="designation.." >
        <input type="text" name="prix_u_min" id="prix_u_min" placeholder="prix unitaire minimale.." >
        <input type="text" name="prix_u_max" id="prix_u_max" placeholder="prix unitaire maximale.." >
        <input type="text" name="quantite_stock" id="quantite_stock" placeholder="quantite_stock.." >
        <select name="categorie_id" id="categorie_id">
          <option value="">Choisir catégorie...</option>
          @foreach($list_categories as $cat)
            <option value="{{$cat->id}}">{{$cat->designation}}</option>
          @endforeach
        </select>
        <input type="submit" value="Rechercher">
      </form>
      <a href="{{route('produits.index')}}">Retour à la liste</a>
    </div>
<h1>Liste des produits</h1>
    <a href="{{route('produits.create')}}">Ajouter un nouveau produit</a>
    <table id="tbl">
      <tr>
          <th>Id</th>
        <th>Designation</th>
        <th>Prix unitaire</th>
        <th>Qauntite stock</th>
        <th>Catégorie</th>
        <th colspan="3">Actions</th>
      </tr>
      @foreach ($produits as $prod)
          <tr>
            <td>{{$prod->id}}</td>
            <td>{{$prod->designation}}</td>
            <td>{{$prod->prix_u}}</td>
            <td>{{$prod->quantite_stock}}</td>
            <td>{{$prod->categorie->designation}}</td>
            <td><a href="{{route('produits.show',$prod->id)}}">Details</a></td>
            <td><a href="{{route('produits.edit',$prod->id)}}">Modifier</a></td>
            <td>
                <form action="{{route('produits.destroy',$prod->id)}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <input type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer ce produit?')">
                </form></td>
          </tr>
      @endforeach
    </table>
    {{$produits->links()}}

@endsection

resources/views/produits/show.blade.php
@extends('layouts.admin')
 @section('title','Détail d\'un produit')
 @section('content')
 <a href="{{route('produits.index')}}">Retourner à la liste des produits</a>
    <h3>ID : {{$produit->id}}</h3>
    <p>Designation : {{$produit->designation}}</p>
    <p>Prix unitaire : {{$produit->prix_u}}</p>
    <p>Quantite_stock : {{$produit->quantite_stock}}</p>
    <p>Categorie : {{$produit->categorie->designation}}</p>
    <div>
        <img src="{{asset('storage/'.$produit->image)}}" alt="photo_produit">
    </div>
    
@endsection